### PR TITLE
fix: added permission handling to CurrentPlaceActivity

### LINKED ISSUE #118: Bug: all buttons in the sample of Kotlin&v3 cause a crash
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
v3
2. OS type and version
Emulator API 30
3. Library version and other environment information
    // GMS
    gmsImplementation 'com.google.android.libraries.places:places:2.4.0'

    // V3
    v3Implementation name:'places-maps-sdk-3.1.0-beta', ext:'aar'
    v3Implementation 'com.android.volley:volley:1.1.1'
    v3Implementation 'com.google.android.gms:play-services-base:17.4.0'
    v3Implementation 'com.google.android.gms:play-services-basement:17.4.0'
    v3Implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    v3Implementation 'com.google.android.gms:play-services-location:17.1.0'
    v3Implementation 'com.google.android.gms:play-services-tasks:17.2.0'
    v3Implementation 'com.google.android.libraries.maps:maps:3.1.0-beta'
    v3Implementation 'com.google.auto.value:auto-value-annotations:1.7.4'
    v3Implementation 'com.google.code.gson:gson:2.8.6'
#### Steps to reproduce

  1. Import attached, which is based on the demo here:

https://github.com/googlemaps/android-places-demos/tree/main/demo-kotlin

#### Code example
It's just what's on the sample.

#### Stack trace
```
2020-10-19 10:43:01.502 32526-32526/com.example.placesdemo.v3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.placesdemo.v3, PID: 32526
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/datatransport/runtime/TransportRuntime;
        at com.google.android.libraries.places.internal.fg.<init>(PG:5)
        at com.google.android.libraries.places.internal.cb.h(PG:17)
        at com.google.android.libraries.places.internal.cb.i(PG:18)
        at com.google.android.libraries.places.internal.cb.l(PG:21)
        at com.google.android.libraries.places.internal.cb.r(PG:27)
        at com.google.android.libraries.places.internal.cb.a(PG:1)
        at com.google.android.libraries.places.api.Places.a(PG:43)
        at com.google.android.libraries.places.api.Places.createClient(PG:30)
        at com.example.placesdemo.CurrentPlaceTestActivity.onCreate(CurrentPlaceTestActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.runtime.TransportRuntime" on path: DexPathList[[zip file "/data/app/~~4e9kwdXxgvYn4L0pRpwLiA==/com.example.placesdemo.v3-SLNdZABmDyGjIHSjoIMU4w==/base.apk"],nativeLibraryDirectories=[/data/app/~~4e9kwdXxgvYn4L0pRpwLiA==/com.example.placesdemo.v3-SLNdZABmDyGjIHSjoIMU4w==/lib/x86, /data/app/~~4e9kwdXxgvYn4L0pRpwLiA==/com.example.placesdemo.v3-SLNdZABmDyGjIHSjoIMU4w==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
```

Following these steps will guarantee the quickest resolution possible.

I've tried each of the buttons. All cause a crash.

See attached:

https://github.com/kataklisma/android-google-places/files/5399937/2020-10-19_10-42-11.zip

And the project (without the real key):

https://github.com/kataklisma/android-google-places/files/5399948/demo-kotlin.zip

### PR DESCRIPTION
**Pull request by kikoso**
This PR adds permissions handling to `CurrentPlaceTestActivity`, which currently was not handling permissions.

- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #118 🦕

### CODE REVIEW

**Comment by wangela** [comment]
@kikoso would you compare these changes with PR #348 and evaluate if we should merge #348 first or if it is obsolete after this PR?

**Comment by kikoso** [comment]
> @kikoso would you compare these changes with PR #348 and evaluate if we should merge #348 first or if it is obsolete after this PR?

The current PR is using contracts to request permissions, which is now the [recommended way](https://developer.android.com/training/permissions/requesting) to do it.

File: demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt [hunk 1]
```diff
@@ -82,31 +108,27 @@ class CurrentPlaceActivity : AppCompatActivity() {
...
-            Toast.makeText(
-                this,
-                "Both ACCESS_WIFI_STATE & ACCESS_FINE_LOCATION permissions are required",
-                Toast.LENGTH_SHORT)
-                .show()
-        }
+        when (PackageManager.PERMISSION_GRANTED) {
+            ContextCompat.checkSelfPermission(
+                applicationContext,
+                permission.ACCESS_COARSE_LOCATION
```
Comment (wangela) [inline demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt:118]: We need to check if either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION is granted. Is there a check like "hasOnePermissionGranted" used in [L149](https://github.com/googlemaps/android-places-demos/pull/348/files#diff-ffc8f0109e203da82714446ad27d274277c3e2c5893e110e0f6a6fe72bd9ecf2R149)?

File: demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt [hunk 2]
```diff
@@ -41,6 +42,30 @@ class CurrentPlaceActivity : AppCompatActivity() {
...
+    val requestPermissionLauncher =
+        registerForActivityResult(
+            ActivityResultContracts.RequestMultiplePermissions()
+        ) { permissions ->
+            when {
+                permissions[permission.ACCESS_FINE_LOCATION] == true -> {
+                    // Precise location access granted.
+                    findCurrentPlaceWithPermissions()
+                }
+                permissions[permission.ACCESS_COARSE_LOCATION] == true -> {
```
Comment (wangela) [inline demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt:55]: Could we simiplify this to a single line with an "OR" case like in [L120 of PR#348](https://github.com/googlemaps/android-places-demos/pull/348/files#diff-ffc8f0109e203da82714446ad27d274277c3e2c5893e110e0f6a6fe72bd9ecf2R120)?

File: demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt [hunk 3]
```diff
@@ -41,6 +42,30 @@ class CurrentPlaceActivity : AppCompatActivity() {
...
+                    // Only approximate location access granted.
+                    findCurrentPlaceWithPermissions()
+                }
+                else -> {
+                    Toast.makeText(
+                        this,
+                        "Both ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION permissions are required",
```
Comment (wangela) [inline demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt:62]: I believe this should be "Either ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission is required.", per [L142](https://github.com/googlemaps/android-places-demos/pull/348/files#diff-ffc8f0109e203da82714446ad27d274277c3e2c5893e110e0f6a6fe72bd9ecf2R142)

**Review by wangela — CHANGES_REQUESTED** [review]
Location permissions are confusing!

File: demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt (hunk 2 above)
Comment (kikoso) [reply demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt:55]: Done.

File: demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt (hunk 1 above)
Comment (kikoso) [reply demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt:118]: Done.

File: demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt (hunk 3 above)
Comment (kikoso) [reply demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt:62]: Jep, I have changed it

**Comment by kikoso** [comment]
> Location permissions are confusing!

I second that. They have changed substantially through a few Android consecutive versions. Probably in a couple of years, they will be more stable.

**Review by wangela — APPROVED** [review]
